 spring:
  profiles:
    active: @profiles@
---
# You can change the default http port
server:
  port: 54321
  contextPath: /meal

logging:
  config: logback.xml

#meal:
#  departments:
#    ids: 1471,2171
#    names: \u65e0\u7ebf\u4e2d\u5fc3\u002f\u5e95\u5c42\u7814\u53d1\u90e8\u002c\u65e0\u7ebf\u4e2d\u5fc3\u002f\u5e94\u7528\u7814\u53d1\u90e8

# Different profiles' configuration
---
spring:
  profiles: default

---
spring:
  profiles: production

