REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Alarm_View_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_HeatMap_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Most_Active_Roamers_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Traffic_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Alarm_Update_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Most_Active_Traffic_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Trending_Traffic_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_Trending_Unique_Roamer_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
Insert into EXPORT_TABLE (RSRC_ID1,RSRC_ID2,REL_TYP_CD,CREATED_DT,MODIFIED_DT,CREATED_BY,MODIFIED_BY,RSRC_TYP_CD) values ('VisPro_UniqueRoamer_GTPC','VisProactive_GTPC','PermissionGroup',to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),to_timestamp('09-OCT-12 04.10.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'cn=directory manager                                                                                ','cn=directory manager                                                                                ','2');
