--where中，威力越到，越放到最后面
-- (低效,执行时间156.3秒) 
SELECT … FROM EMP E WHERE
	SAL > 50000
	AND JOB = 'MANAGER'
	AND 25 < (SELECT COUNT(*) FROM EMP WHERE MGR=E.EMPNO); 
	
--在许多基于基础表的查询中,为了满足一个条件,往往需要对另一个表进行联接.
--在这种情况下, 使用EXISTS(或NOT EXISTS)通常将提高查询的效率.
--低效 
SELECT * FROM EMP (基础表)
WHERE EMPNO > 0
AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'MELB')
--高效
SELECT * FROM EMP (基础表)
WHERE EMPNO > 0
AND EXISTS (SELECT 'X' FROM DEPT WHERE DEPT.DEPTNO = EMP.DEPTNO AND LOC = 'MELB')

--在子查询中,NOT IN子句将执行一个内部的排序和合并. 无论在哪种情况下,NOT IN都是最低效的 (因为它对子查询中的表执行了一个全表遍历). 
-- 为了避免使用NOT IN ,我们可以把它改写成外连接(Outer Joins)或NOT EXISTS. 

--低效
SELECT … FROM EMP 
WHERE DEPT_NO NOT IN (SELECT DEPT_NO FROM DEPT WHERE DEPT_CAT='A'); 
--高效
SELECT … FROM EMP A,DEPT B
WHERE A.DEPT_NO = B.DEPT(+)
AND B.DEPT_NO IS NULL
AND B.DEPT_CAT(+) = 'A'
--最高效
SELECT … FROM EMP E
WHERE NOT EXISTS (SELECT 'X' FROM DEPT D WHERE D.DEPT_NO = E.DEPT_NO AND DEPT_CAT = 'A'); 

--通常来说 , 采用表连接的方式比EXISTS更有效率
--高效
SELECT ENAME FROM EMP E 
WHERE EXISTS (SELECT 'X' FROM DEPT WHERE DEPT_NO = E.DEPT_NO AND DEPT_CAT = 'A');
--更高效
SELECT ENAME FROM DEPT D,EMP E
WHERE E.DEPT_NO = D.DEPT_NO AND DEPT_CAT = 'A' ; 


 
