//
DROP TABLE EI.LTABLE;
CREATE TABLE EI.LTABLE (
        L_ID INTEGER NOT NULL,
        L_DESCRIPTION VARCHAR (100),
        CONSTRAINT PK_LTABLE PRIMARY KEY (L_ID)
    );
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (3, 'L 3');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (9, 'L 9');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (4, 'L 4');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (5, 'L 5');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (6, 'L 6');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (7, 'L 7');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (8, 'L 8');
INSERT INTO EI.LTABLE(L_ID, L_DESCRIPTION) VALUES (10, 'L 10');

DROP TABLE EI.RTABLE;
CREATE TABLE EI.RTABLE (
        R_ID INTEGER NOT NULL,
        R_DESCRIPTION VARCHAR (100),
        CONSTRAINT PK_RTABLE PRIMARY KEY (R_ID)
    );
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (5, 'R 5');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (6, 'R 6');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (7, 'R 7');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (8, 'R 8');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (9, 'R 9');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (10, 'R 10');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (11, 'R 11');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (12, 'R 12');
INSERT INTO EI.RTABLE(R_ID, R_DESCRIPTION) VALUES (13, 'R 13');


-- Left join 时，位于On 和 位于where 中的不同
SELECT * FROM EI.LTABLE LEFT JOIN EI.RTABLE ON (L_ID>R_ID AND L_ID=8);
SELECT * FROM EI.LTABLE LEFT JOIN EI.RTABLE ON (L_ID>R_ID) WHERE L_ID=8;

SELECT * FROM EI.LTABLE LEFT JOIN EI.RTABLE ON (L_ID>4 and R_ID=8);
SELECT * FROM EI.LTABLE LEFT JOIN EI.RTABLE ON (L_ID<4 OR R_ID>100);
SELECT * FROM EI.LTABLE LEFT JOIN EI.RTABLE ON (L_ID<4 OR R_ID>12);




